# Generated by Django 5.2.10 on 2026-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='structure')),
                ('budget', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('read', models.BooleanField(default=False, verbose_name='lu')),
            ],
            options={
                'verbose_name': 'message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120, verbose_name='poste')),
                ('company', models.CharField(max_length=120, verbose_name='structure')),
                ('location', models.CharField(blank=True, max_length=80, verbose_name='lieu')),
                ('start', models.DateField(verbose_name='début')),
                ('end', models.DateField(blank=True, help_text='Vide = en cours', null=True, verbose_name='fin')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'expérience',
                'ordering': ['order', '-start'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveSmallIntegerField(verbose_name='année')),
                ('category', models.CharField(help_text='Ex. WebGL, E-commerce, SaaS', max_length=60, verbose_name='catégorie')),
                ('summary', models.TextField(max_length=400, verbose_name='résumé')),
                ('stack', models.CharField(blank=True, help_text='Technologies séparées par des virgules', max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='projects/', verbose_name='visuel')),
                ('accent', models.CharField(default='#D4FF3A', help_text='Hex, utilisé quand il n’y a pas de visuel', max_length=7, verbose_name='couleur')),
                ('live_url', models.URLField(blank=True, verbose_name='lien du site')),
                ('repo_url', models.URLField(blank=True, verbose_name='lien du code')),
                ('featured', models.BooleanField(default=True, verbose_name='mis en avant')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'projet',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('group', models.CharField(choices=[('frontend', 'Front-end'), ('backend', 'Back-end'), ('creative', 'Creative / Motion'), ('tooling', 'Outils / DevOps')], max_length=20, verbose_name='groupe')),
                ('level', models.PositiveSmallIntegerField(default=80, verbose_name='niveau (0-100)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'compétence',
                'ordering': ['group', 'order', 'name'],
            },
        ),
    ]
