# Generated by Django 5.2.10 on 2026-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, choices=[('design', 'Design graphique'), ('dev', 'Développement'), ('both', 'Les deux')], max_length=10, verbose_name='besoin'),
        ),
        migrations.AddField(
            model_name='project',
            name='pole',
            field=models.CharField(choices=[('design', 'Design graphique'), ('dev', 'Développement logiciel')], default='dev', max_length=10, verbose_name='pôle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(help_text='Ex. Identité visuelle, Print, WebGL, SaaS', max_length=60, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='group',
            field=models.CharField(choices=[('design', 'Design graphique'), ('frontend', 'Front-end'), ('backend', 'Back-end'), ('creative', 'Creative / Motion'), ('tooling', 'Outils / DevOps')], max_length=20, verbose_name='groupe'),
        ),
    ]
