# Generated by Django 5.2.10 on 2026-10-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_service_project_pole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accent',
            field=models.CharField(default='#FF6E10', help_text='Hex, utilisé quand il n’y a pas de visuel', max_length=7, verbose_name='couleur'),
        ),
    ]
