# Generated by Django 5.2.10 on 2026-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='kind',
            field=models.CharField(choices=[('work', 'Expérience'), ('education', 'Formation'), ('side', 'Freelance / projet')], default='work', help_text='Formation et freelance apparaissent hachurés sur la timeline', max_length=10, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='experience',
            name='pole',
            field=models.CharField(choices=[('design', 'Design graphique'), ('dev', 'Développement'), ('both', 'Les deux')], default='dev', max_length=10, verbose_name='pôle'),
        ),
    ]
