# Generated by Django 5.2.10 on 2026-10-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_kind_experience_pole'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='description (EN)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='poste (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True, help_text='Esquisses, choix graphiques, choix techniques', verbose_name='démarche'),
        ),
        migrations.AddField(
            model_name='project',
            name='approach_en',
            field=models.TextField(blank=True, verbose_name='démarche (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='category_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='catégorie (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.TextField(blank=True, help_text='Le brief, le client, le problème', verbose_name='contexte'),
        ),
        migrations.AddField(
            model_name='project',
            name='context_en',
            field=models.TextField(blank=True, verbose_name='contexte (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, help_text='Ce qui a été livré, les chiffres', verbose_name='résultat'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_en',
            field=models.TextField(blank=True, verbose_name='résultat (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Ex. Identité visuelle, développement front', max_length=160, verbose_name='rôle'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='rôle (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_en',
            field=models.TextField(blank=True, max_length=400, verbose_name='résumé (EN)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='nom (EN)'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='légende (EN)')),
                ('wide', models.BooleanField(default=False, verbose_name='pleine largeur')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'image',
                'ordering': ['order', 'id'],
            },
        ),
    ]
