# Generated by Django 5.2.10 on 2026-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience_description_en_experience_role_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='group',
            field=models.CharField(choices=[('design', 'Design graphique'), ('frontend', 'Front-end & mobile'), ('backend', 'Back-end'), ('creative', 'Creative / Motion'), ('tooling', 'DevOps & outils')], max_length=20, verbose_name='groupe'),
        ),
    ]
